### ISSUE TITLE
system images will be reinstalled on every puppet run

### ISSUE THREAD

**Issue by cintiadr** [maestrodev/puppet-android#37]
So, I'm installing:

```
android::system_images { ['sys-img-armeabi-v7a-android-22', 'sys-img-x86_64-android-22', 'sys-img-x86-android-22']: }
```

This is the logic to run the exec [package.pp#L35](https://github.com/maestrodev/puppet-android/blob/master/manifests/package.pp#L35):
```
   'system-images': {
      $title_parts = split($title, '-')
      $creates = "${android::paths::sdk_home}/system-images/android-${title_parts[1]}"
    }
```
```title_parts[1]``` is resolved to ```img```, or something which is not the platform of android. The paths you want are, instead:
  * ${android::paths::sdk_home}/system-images/android-22/default/armeabi-v7a  
  * ${android::paths::sdk_home}/system-images/android-22/default/x86  
  * ${android::paths::sdk_home}/system-images/android-22/default/x86_64

I tried with system images of other platforms too, and they were all installed on the same place. I'm using SDK '24.3.3', maybe that's the reason why it changed.

**Comment by tmclaugh** [comment]
I can confirm this behavior too.  Any clue when the layout changed?

**Comment by tmclaugh** [comment]
PR filed.
